steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA"
      - .

  # Push to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA"

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - "$_SERVICE_NAME"
      - --image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --timeout=600

images:
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA"

substitutions:
  _SERVICE_NAME: sbic-manual-trigger
  _REGION: asia-southeast1
  _REPOSITORY: cloud-run-source-deploy
